// src/constants/timezones.ts

export const TIMEZONES = [
  { value: "Asia/Kathmandu", label: "Nepal Time (GMT+05:45)" },
  { value: "Australia/Sydney", label: "Sydney, Melbourne, Canberra (GMT+10 / GMT+11)" },
  { value: "Australia/Brisbane", label: "Brisbane (GMT+10)" },
  { value: "Australia/Adelaide", label: "Adelaide (GMT+09:30 / GMT+10:30)" },
  { value: "Australia/Darwin", label: "Darwin (GMT+09:30)" },
  { value: "Australia/Perth", label: "Perth (GMT+08:00)" },
  { value: "Australia/Hobart", label: "Hobart (GMT+10 / GMT+11)" },
  { value: "Australia/Lord_Howe", label: "Lord Howe Island (GMT+10:30 / GMT+11)" },
  { value: "Antarctica/Macquarie", label: "Macquarie Island (GMT+10 / GMT+11)" },
  { value: "Pacific/Honolulu", label: "Hawaii (GMT-10)" },
  { value: "America/Los_Angeles", label: "Pacific Time (GMT-8 / GMT-7)" },
  { value: "America/Denver", label: "Mountain Time (GMT-7 / GMT-6)" },
  { value: "America/Chicago", label: "Central Time (GMT-6 / GMT-5)" },
  { value: "America/New_York", label: "Eastern Time (GMT-5 / GMT-4)" },
  { value: "Europe/London", label: "London (GMT+0 / GMT+1)" },
  { value: "Europe/Berlin", label: "Berlin (GMT+1 / GMT+2)" },
  { value: "Europe/Paris", label: "Paris (GMT+1 / GMT+2)" },
  { value: "Europe/Moscow", label: "Moscow (GMT+3)" },
  { value: "Asia/Dubai", label: "Dubai (GMT+4)" },
  { value: "Asia/Kolkata", label: "India Standard Time (GMT+5:30)" },
  { value: "Asia/Bangkok", label: "Bangkok (GMT+7)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (GMT+8)" },
  { value: "Asia/Tokyo", label: "Tokyo (GMT+9)" },
];

export const tzMap: Record<string, string> = {
  "Asia/Kathmandu": "Nepal",
  "America/New_York": "Eastern",
  "America/Los_Angeles": "Pacific",
  "Europe/London": "London",
  "Asia/Tokyo": "Japan",
  "Asia/Dubai": "Dubai",
  "Asia/Kolkata": "India",
  "Europe/Berlin": "Berlin",
  "Europe/Paris": "Paris",
  "Europe/Moscow": "Moscow",
  "Pacific/Honolulu": "Hawaii",
  "Australia/Sydney": "Sydney",
  "Australia/Brisbane": "Brisbane",
  "Australia/Adelaide": "Adelaide",
  "Australia/Darwin": "Darwin",
  "Australia/Perth": "Perth",
  "Australia/Hobart": "Hobart",
  "Australia/Lord_Howe": "Lord Howe",
  "Antarctica/Macquarie": "Macquarie",
};

