/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as SchedulingIndexRouteImport } from './routes/scheduling/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as AvailabilityIndexRouteImport } from './routes/availability/index'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'
import { Route as BookingsConfirmationRouteImport } from './routes/bookings/confirmation'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings/$bookingId'
import { Route as authForgetPasswordRouteImport } from './routes/(auth)/forget-password'
import { Route as MeetingsUserSlugEventSlugRouteImport } from './routes/meetings/$userSlug/$eventSlug'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingIndexRoute = SchedulingIndexRouteImport.update({
  id: '/scheduling/',
  path: '/scheduling/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityIndexRoute = AvailabilityIndexRouteImport.update({
  id: '/availability/',
  path: '/availability/',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsConfirmationRoute = BookingsConfirmationRouteImport.update({
  id: '/bookings/confirmation',
  path: '/bookings/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgetPasswordRoute = authForgetPasswordRouteImport.update({
  id: '/(auth)/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsUserSlugEventSlugRoute =
  MeetingsUserSlugEventSlugRouteImport.update({
    id: '/meetings/$userSlug/$eventSlug',
    path: '/meetings/$userSlug/$eventSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/logout': typeof LogoutRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/bookings/confirmation': typeof BookingsConfirmationRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof authIndexRoute
  '/availability': typeof AvailabilityIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/meetings/$userSlug/$eventSlug': typeof MeetingsUserSlugEventSlugRoute
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/bookings/confirmation': typeof BookingsConfirmationRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof authIndexRoute
  '/availability': typeof AvailabilityIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/meetings/$userSlug/$eventSlug': typeof MeetingsUserSlugEventSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/logout': typeof LogoutRoute
  '/(auth)/forget-password': typeof authForgetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/bookings/confirmation': typeof BookingsConfirmationRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/(auth)/': typeof authIndexRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/meetings/$userSlug/$eventSlug': typeof MeetingsUserSlugEventSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/logout'
    | '/forget-password'
    | '/bookings/$bookingId'
    | '/bookings/confirmation'
    | '/customers/$customerId'
    | '/oauth/callback'
    | '/'
    | '/availability'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/meetings'
    | '/profile'
    | '/scheduling'
    | '/meetings/$userSlug/$eventSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | '/forget-password'
    | '/bookings/$bookingId'
    | '/bookings/confirmation'
    | '/customers/$customerId'
    | '/oauth/callback'
    | '/'
    | '/availability'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/meetings'
    | '/profile'
    | '/scheduling'
    | '/meetings/$userSlug/$eventSlug'
  id:
    | '__root__'
    | '/logout'
    | '/(auth)/forget-password'
    | '/bookings/$bookingId'
    | '/bookings/confirmation'
    | '/customers/$customerId'
    | '/oauth/callback'
    | '/(auth)/'
    | '/availability/'
    | '/bookings/'
    | '/customers/'
    | '/dashboard/'
    | '/meetings/'
    | '/profile/'
    | '/scheduling/'
    | '/meetings/$userSlug/$eventSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LogoutRoute: typeof LogoutRoute
  authForgetPasswordRoute: typeof authForgetPasswordRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  BookingsConfirmationRoute: typeof BookingsConfirmationRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  authIndexRoute: typeof authIndexRoute
  AvailabilityIndexRoute: typeof AvailabilityIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SchedulingIndexRoute: typeof SchedulingIndexRoute
  MeetingsUserSlugEventSlugRoute: typeof MeetingsUserSlugEventSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/': {
      id: '/scheduling/'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability/': {
      id: '/availability/'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/confirmation': {
      id: '/bookings/confirmation'
      path: '/bookings/confirmation'
      fullPath: '/bookings/confirmation'
      preLoaderRoute: typeof BookingsConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forget-password': {
      id: '/(auth)/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof authForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$userSlug/$eventSlug': {
      id: '/meetings/$userSlug/$eventSlug'
      path: '/meetings/$userSlug/$eventSlug'
      fullPath: '/meetings/$userSlug/$eventSlug'
      preLoaderRoute: typeof MeetingsUserSlugEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LogoutRoute: LogoutRoute,
  authForgetPasswordRoute: authForgetPasswordRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  BookingsConfirmationRoute: BookingsConfirmationRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  authIndexRoute: authIndexRoute,
  AvailabilityIndexRoute: AvailabilityIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SchedulingIndexRoute: SchedulingIndexRoute,
  MeetingsUserSlugEventSlugRoute: MeetingsUserSlugEventSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
