/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SchedulingIndexRouteImport } from './routes/scheduling/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as AvailabilityIndexRouteImport } from './routes/availability/index'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings/$bookingId'
import { Route as authForgetPasswordRouteImport } from './routes/(auth)/forget-password'

const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingIndexRoute = SchedulingIndexRouteImport.update({
  id: '/scheduling/',
  path: '/scheduling/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityIndexRoute = AvailabilityIndexRouteImport.update({
  id: '/availability/',
  path: '/availability/',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgetPasswordRoute = authForgetPasswordRouteImport.update({
  id: '/(auth)/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/forget-password': typeof authForgetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/': typeof authIndexRoute
  '/availability': typeof AvailabilityIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forget-password': typeof authForgetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/': typeof authIndexRoute
  '/availability': typeof AvailabilityIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/scheduling': typeof SchedulingIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/forget-password': typeof authForgetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/(auth)/': typeof authIndexRoute
  '/availability/': typeof AvailabilityIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/scheduling/': typeof SchedulingIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forget-password'
    | '/bookings/$bookingId'
    | '/customers/$customerId'
    | '/'
    | '/availability'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/scheduling'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forget-password'
    | '/bookings/$bookingId'
    | '/customers/$customerId'
    | '/'
    | '/availability'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/scheduling'
    | '/settings'
  id:
    | '__root__'
    | '/(auth)/forget-password'
    | '/bookings/$bookingId'
    | '/customers/$customerId'
    | '/(auth)/'
    | '/availability/'
    | '/bookings/'
    | '/customers/'
    | '/dashboard/'
    | '/scheduling/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authForgetPasswordRoute: typeof authForgetPasswordRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  authIndexRoute: typeof authIndexRoute
  AvailabilityIndexRoute: typeof AvailabilityIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SchedulingIndexRoute: typeof SchedulingIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling/': {
      id: '/scheduling/'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability/': {
      id: '/availability/'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forget-password': {
      id: '/(auth)/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof authForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authForgetPasswordRoute: authForgetPasswordRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  authIndexRoute: authIndexRoute,
  AvailabilityIndexRoute: AvailabilityIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SchedulingIndexRoute: SchedulingIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
