/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authForgetPasswordRouteImport } from './routes/(auth)/forget-password'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgetPasswordRoute = authForgetPasswordRouteImport.update({
  id: '/(auth)/forget-password',
  path: '/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/': typeof authIndexRoute
}
export interface FileRoutesByTo {
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/forget-password': typeof authForgetPasswordRoute
  '/': typeof authIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/availability': typeof AvailabilityRoute
  '/bookings': typeof BookingsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/(auth)/forget-password': typeof authForgetPasswordRoute
  '/(auth)/': typeof authIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/availability'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/scheduling'
    | '/settings'
    | '/forget-password'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/availability'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/scheduling'
    | '/settings'
    | '/forget-password'
    | '/'
  id:
    | '__root__'
    | '/availability'
    | '/bookings'
    | '/customers'
    | '/dashboard'
    | '/scheduling'
    | '/settings'
    | '/(auth)/forget-password'
    | '/(auth)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AvailabilityRoute: typeof AvailabilityRoute
  BookingsRoute: typeof BookingsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  SchedulingRoute: typeof SchedulingRoute
  SettingsRoute: typeof SettingsRoute
  authForgetPasswordRoute: typeof authForgetPasswordRoute
  authIndexRoute: typeof authIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forget-password': {
      id: '/(auth)/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof authForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AvailabilityRoute: AvailabilityRoute,
  BookingsRoute: BookingsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  SchedulingRoute: SchedulingRoute,
  SettingsRoute: SettingsRoute,
  authForgetPasswordRoute: authForgetPasswordRoute,
  authIndexRoute: authIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
